load("//:generate_env.bzl", "micromamba_env_repository")
micromamba_env_repository(name = "micromamba_env")

load("@micromamba_env//:micromamba_root.bzl", "MAMBA_ENV")

new_local_repository(
    name = "gtest_repo",
    path = MAMBA_ENV,
    build_file_content = """
package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "gtest",
    srcs = ["lib/libgtest.so", "lib/libgtest_main.so"],
    hdrs = glob(["include/gtest/**/*.h"]),
    strip_include_prefix = "/include",
)
""",
)